# Generated by Django 5.2.6 on 2025-09-21 08:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year', '-name']},
        ),
        migrations.AddField(
            model_name='historicalyear',
            name='year',
            field=models.IntegerField(blank=True, help_text='Four-digit year as integer', null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.IntegerField(blank=True, help_text='Four-digit year as integer', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalBrandModelSeries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, help_text='Optional series/generation name', max_length=100)),
                ('year_start', models.IntegerField(help_text='First year this series was available')),
                ('year_end', models.IntegerField(blank=True, help_text='Last year (leave empty if ongoing)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.brand')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.model')),
            ],
            options={
                'verbose_name': 'historical brand model series',
                'verbose_name_plural': 'historical Brand Model Series',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BrandModelSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, help_text='Optional series/generation name', max_length=100)),
                ('year_start', models.IntegerField(help_text='First year this series was available')),
                ('year_end', models.IntegerField(blank=True, help_text='Last year (leave empty if ongoing)', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_series', to='maker.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_series', to='maker.model')),
                ('packages', models.ManyToManyField(blank=True, related_name='brand_model_series', to='maker.package')),
            ],
            options={
                'verbose_name_plural': 'Brand Model Series',
                'ordering': ['brand__name', 'model__name', '-year_start'],
                'unique_together': {('brand', 'model', 'year_start')},
            },
        ),
    ]
