# Generated by Django 5.2.6 on 2025-09-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_add_year_integer_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='historicalyear',
            name='name',
        ),
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
        migrations.AlterField(
            model_name='historicalyear',
            name='year',
            field=models.IntegerField(db_index=True, default=2025, help_text='Four-digit year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(default=2025, help_text='Four-digit year', unique=True),
            preserve_default=False,
        ),
    ]
