# Generated by Django 5.2.6 on 2025-09-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_finalize_year_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodelseries',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='brand_model_series',
            field=models.ManyToManyField(related_name='packages', to='maker.brandmodelseries'),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
