# Generated by Django 5.2.6 on 2025-09-21 11:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_remove_brandmodelseries_packages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalmatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical match', 'verbose_name_plural': 'historical Matches'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['id'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='brandmodelseries',
            name='series_name',
        ),
        migrations.RemoveField(
            model_name='historicalbrandmodelseries',
            name='series_name',
        ),
        migrations.RemoveField(
            model_name='historicalmatch',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='match',
            name='blurb',
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional brand filter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.brand'),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional model filter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.model'),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='Optional latest model year', null=True),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='Optional earliest model year', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional brand filter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='maker.brand'),
        ),
        migrations.AddField(
            model_name='match',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Optional model filter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='maker.model'),
        ),
        migrations.AddField(
            model_name='match',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='Optional latest model year', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='Optional earliest model year', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalMatchItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('placement', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('highlights', 'Highlights'), ('options', 'Options')], help_text='Content category for this item', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Selection priority (higher numbers selected first when space is limited)')),
                ('sequence', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blurb', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.blurb')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.match')),
            ],
            options={
                'verbose_name': 'historical Match Item',
                'verbose_name_plural': 'historical Match Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical series',
                'verbose_name_plural': 'historical Series',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('highlights', 'Highlights'), ('options', 'Options')], help_text='Content category for this item', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Selection priority (higher numbers selected first when space is limited)')),
                ('sequence', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('blurb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_items', to='maker.blurb')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maker.match')),
            ],
            options={
                'verbose_name': 'Match Item',
                'verbose_name_plural': 'Match Items',
                'ordering': ['placement', 'sequence', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='brandmodelseries',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Optional series/generation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_model_series', to='maker.series'),
        ),
        migrations.AddField(
            model_name='historicalbrandmodelseries',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional series/generation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.series'),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional series filter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.series'),
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Optional series filter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='maker.series'),
        ),
    ]
