# Generated by Django 5.2.6 on 2025-09-21 12:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0005_series_alter_historicalmatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurbGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this group represents')),
                ('max_items', models.IntegerField(default=1, help_text='Maximum items from this group allowed in content (1=replacement logic)')),
            ],
            options={
                'verbose_name': 'Blurb Group',
                'verbose_name_plural': 'Blurb Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blurb',
            name='group_priority',
            field=models.IntegerField(default=0, help_text='Priority within blurb group (higher values win in replacement)'),
        ),
        migrations.AddField(
            model_name='historicalblurb',
            name='group_priority',
            field=models.IntegerField(default=0, help_text='Priority within blurb group (higher values win in replacement)'),
        ),
        migrations.AddField(
            model_name='blurb',
            name='blurb_group',
            field=models.ForeignKey(blank=True, help_text='Blurb group for exclusion/replacement logic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blurbs', to='maker.blurbgroup'),
        ),
        migrations.AddField(
            model_name='historicalblurb',
            name='blurb_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Blurb group for exclusion/replacement logic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.blurbgroup'),
        ),
        migrations.CreateModel(
            name='HistoricalBlurbGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this group represents')),
                ('max_items', models.IntegerField(default=1, help_text='Maximum items from this group allowed in content (1=replacement logic)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Blurb Group',
                'verbose_name_plural': 'historical Blurb Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
