# Generated by Django 5.2.6 on 2025-09-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_blurbgroup_blurb_group_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional package filter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.package'),
        ),
        migrations.AddField(
            model_name='match',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Optional package filter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='maker.package'),
        ),
    ]
