# Generated by Django 5.2.6 on 2025-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_historicalmatch_package_match_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='text',
            field=models.CharField(help_text='Marketing text (max 35 characters)', max_length=35),
        ),
        migrations.AlterField(
            model_name='historicalblurb',
            name='text',
            field=models.CharField(help_text='Marketing text (max 35 characters)', max_length=35),
        ),
    ]
