# Generated by Django 5.2.6 on 2025-09-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_alter_blurb_text_alter_historicalblurb_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatchitem',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='Check to also show this item in Highlights'),
        ),
        migrations.AddField(
            model_name='historicalmatchitem',
            name='is_option',
            field=models.BooleanField(default=False, help_text='Check to also show this item in Options'),
        ),
        migrations.AddField(
            model_name='matchitem',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='Check to also show this item in Highlights'),
        ),
        migrations.AddField(
            model_name='matchitem',
            name='is_option',
            field=models.BooleanField(default=False, help_text='Check to also show this item in Options'),
        ),
        migrations.AlterField(
            model_name='historicalmatchitem',
            name='placement',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], help_text='Primary content category (Interior or Exterior)', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='placement',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], help_text='Primary content category (Interior or Exterior)', max_length=20),
        ),
    ]
