# Generated by Django 5.2.6 on 2025-09-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0010_migrate_placement_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchitem',
            options={'ordering': ['placement', 'sequence'], 'verbose_name': 'Match Item', 'verbose_name_plural': 'Match Items'},
        ),
        migrations.RemoveField(
            model_name='historicalmatchitem',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='matchitem',
            name='priority',
        ),
    ]
