# Generated by Django 5.2.6 on 2025-10-05 15:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0011_remove_matchitem_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurbInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo or drawing for back office reference', upload_to='blurb_info/')),
                ('info_text', models.TextField(blank=True, help_text='Technical details or additional information')),
                ('sequence', models.IntegerField(default=0, help_text='Display order for multiple images (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blurb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blurb_info', to='maker.blurb')),
            ],
            options={
                'verbose_name': 'Blurb Info',
                'verbose_name_plural': 'Blurb Info',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBlurbInfo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(help_text='Photo or drawing for back office reference', max_length=100)),
                ('info_text', models.TextField(blank=True, help_text='Technical details or additional information')),
                ('sequence', models.IntegerField(default=0, help_text='Display order for multiple images (lower numbers appear first)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blurb', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maker.blurb')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Blurb Info',
                'verbose_name_plural': 'historical Blurb Info',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
